### PR TITLE
Correctly handle prototype property names passed as codes

### LINKED ISSUE #20: .validate behaves incorrectly for prototype property names as code
The core `ISO6391.validate` method behaves incorrectly for prototype property names provided as `code` parameters, e.g. `"toString"`.

```js
const ISO6391 = require('iso-639-1')
it('toString', function() {
  assert.equal(ISO6391.validate('toString'), false);  // fails: returns `true` unexpectedly
});
```

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #20

### CODE REVIEW

**Comment by zeke** [comment]
Nice!

**Comment by zeke** [comment]
@meikidd I notice the [GitHub releases](https://github.com/meikidd/iso-639-1/releases) are out of alignment with the npm releases -- did this change land in the latest npm release?

**Comment by JamesMGreene** [comment]
@zeke Looks like it did: https://unpkg.com/iso-639-1@2.1.0/build/index.js

```js
{
  key: 'validate',
  value: function validate(code) {
    return _data2.default.hasOwnProperty(code);
  }
}
```

@meikidd Please add the `2.1.0` release to your GitHub Releases when you get a chance. Thank you for the quick turnaround! ✨

**Comment by meikidd** [comment]
@JamesMGreene , done 😄

**Comment by JamesMGreene** [comment]
Thank you! ✨

**Pull request merged**
